# Generated by Django 4.0.2 on 2022-03-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_profileposts_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileposts',
            name='language',
            field=models.CharField(default='EN', max_length=10),
        ),
    ]
