# Generated by Django 4.0.3 on 2022-03-24 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_profileposts_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorcount',
            name='visitor_count',
            field=models.IntegerField(default=1),
        ),
    ]
