# Generated by Django 4.0.3 on 2022-05-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=50)),
                ('housenumber', models.IntegerField(blank=True, null=True)),
                ('housenumber_add', models.CharField(max_length=15)),
                ('zipcode', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('municipality', models.CharField(max_length=60)),
                ('province', models.CharField(max_length=60)),
                ('ask_price', models.FloatField()),
                ('construction_year', models.IntegerField(blank=True, null=True)),
                ('amount_rooms', models.IntegerField(default=0, null=True)),
                ('description', models.TextField()),
                ('thumbnail_photo', models.ImageField(upload_to='')),
                ('other_photos', models.ImageField(upload_to='')),
            ],
        ),
    ]
