# Generated by Django 4.0.3 on 2022-05-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymodel',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='housenumber_add',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='municipality',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='other_photos',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='province',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='street',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='thumbnail_photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
