# Generated by Django 4.0.3 on 2022-05-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_projects', '0003_propertymodel_added_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymodel',
            name='thumbnail_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
