# Generated by Django 4.0.3 on 2022-05-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_projects', '0004_alter_propertymodel_thumbnail_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymodel',
            name='ask_price',
            field=models.IntegerField(),
        ),
    ]
