# Generated by Django 4.0.3 on 2022-05-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_projects', '0005_alter_propertymodel_ask_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymodel',
            name='other_photos',
            field=models.FileField(blank=True, default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='thumbnail_photo',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
