# Generated by Django 4.0.3 on 2022-05-17 06:10

import core.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_projects', '0006_alter_propertymodel_other_photos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymodel',
            name='other_photos',
            field=models.FileField(blank=True, storage=core.storage_backends.PublicMediaStorage, upload_to=''),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='thumbnail_photo',
            field=models.FileField(blank=True, storage=core.storage_backends.PublicMediaStorage, upload_to=''),
        ),
    ]
