# Generated by Django 4.0.3 on 2022-05-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_projects', '0008_alter_propertymodel_ask_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymodel',
            name='perceel_oppervlak',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='propertymodel',
            name='woon_oppervlak',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
