# Generated by Django 4.0.3 on 2022-05-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_projects', '0009_propertymodel_perceel_oppervlak_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymodel',
            name='type_of_property',
            field=models.CharField(blank=True, choices=[('SL', 'Sale'), ('RT', 'Rental')], default='SL', max_length=5, null=True),
        ),
    ]
