# Generated by Django 4.0.3 on 2022-05-22 08:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('website_projects', '0010_propertymodel_type_of_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymodel',
            name='temp_id',
            field=models.UUIDField(default=uuid.UUID('0687288a-7254-4ffe-92ff-972b078cbba4'), editable=False, unique=True),
        ),
    ]
