# Generated by Django 4.0.3 on 2022-05-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_projects', '0012_remove_propertymodel_temp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymodel',
            name='building_type',
            field=models.CharField(blank=True, choices=[('TOO', '2-onder-1-kapwoning'), ('EH', 'Eindwoning'), ('TH', 'Geschakelde woning'), ('COH', 'Hoekwoning'), ('IBH', 'Tussenwoning'), ('DH', 'Vrijstaande woning'), ('AP', 'Appartement'), ('NONE', 'Onbekend')], default='NONE', max_length=20, null=True),
        ),
    ]
