# Generated by Django 4.0.3 on 2022-05-25 06:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('website_projects', '0013_propertymodel_building_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymodel',
            name='property_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
