# Generated by Django 4.0.3 on 2022-05-28 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_projects', '0015_propertymodel_status_alter_propertymodel_ask_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymodel',
            name='status',
            field=models.CharField(choices=[('SD', 'Verkocht'), ('UO', 'Onder bod'), ('SWR', 'Verkocht onder voorbehoud'), ('AV', 'Beschikbaar'), ('NONE', 'Onbekend')], default='NONE', max_length=40, null=True),
        ),
    ]
