# Generated by Django 4.0.3 on 2022-05-31 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_projects', '0016_alter_propertymodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymodel',
            name='ask_price_suffix',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
