# Generated by Django 4.0.3 on 2022-06-03 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_projects', '0017_propertymodel_ask_price_suffix'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymodel',
            name='energy_label',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='ask_price_suffix',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='building_type',
            field=models.CharField(blank=True, choices=[('TOO', '2-onder-1-kapwoning'), ('EH', 'Eindwoning'), ('TH', 'Geschakelde woning'), ('COH', 'Hoekwoning'), ('IBH', 'Tussenwoning'), ('DH', 'Vrijstaande woning'), ('AP', 'Appartement'), ('NONE', 'Onbekend')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='housenumber_add',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='municipality',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='province',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='status',
            field=models.CharField(blank=True, choices=[('SD', 'Verkocht'), ('UO', 'Onder bod'), ('SWR', 'Verkocht onder voorbehoud'), ('AV', 'Beschikbaar'), ('NONE', 'Onbekend')], default='NONE', max_length=40),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='street',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='type_of_property',
            field=models.CharField(blank=True, choices=[('SL', 'Sale'), ('RT', 'Rental')], default='SL', max_length=5),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='zipcode',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
