# Generated by Django 4.0.3 on 2022-06-03 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_projects', '0018_propertymodel_energy_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymodel',
            name='type_of_heating',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
