# Generated by Django 4.0.3 on 2022-06-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_projects', '0021_propertymodel_rental_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymodel',
            name='rental_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
