# Generated by Django 4.0.3 on 2022-06-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_projects', '0024_alter_propertymodel_other_photos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapyPropertyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=40)),
                ('housenumber', models.IntegerField(blank=True, null=True)),
                ('housenumber_add', models.CharField(blank=True, default='', max_length=15)),
                ('zipcode', models.CharField(blank=True, default='', max_length=10)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('municipality', models.CharField(blank=True, default='', max_length=60)),
                ('type_of_property', models.CharField(blank=True, max_length=30)),
                ('ask_price', models.IntegerField(default=0)),
                ('amount_rooms', models.IntegerField(default=0, null=True)),
                ('woon_oppervlak', models.IntegerField(blank=True, default=0, null=True)),
                ('perceel_oppervlak', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
