# Generated by Django 4.0.3 on 2022-07-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_projects', '0025_scrapypropertymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapypropertymodel',
            name='status',
            field=models.CharField(choices=[('Verkocht', 'Verkocht'), ('Onder bod', 'Onder bod'), ('Verkocht onder voorbehoud', 'Verkocht onder voorbehoud'), ('Beschikbaar', 'Beschikbaar'), ('Te koop', 'Te koop'), ('Onbekend', 'Onbekend')], default='', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Verkocht', 'Verkocht'), ('Onder bod', 'Onder bod'), ('Verkocht onder voorbehoud', 'Verkocht onder voorbehoud'), ('Beschikbaar', 'Beschikbaar'), ('Te koop', 'Te koop'), ('Onbekend', 'Onbekend')], default='Onbekend', max_length=40),
        ),
    ]
