# Generated by Django 4.0.3 on 2022-07-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_projects', '0026_scrapypropertymodel_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapypropertymodel',
            name='date_sold',
            field=models.DateField(blank=True, null=True),
        ),
    ]
