# Generated by Django 4.0.2 on 2022-03-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_projects', '0005_alter_portfolio_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='positions',
            name='quantity',
            field=models.FloatField(default=1),
        ),
    ]
