# Generated by Django 4.0.2 on 2022-03-13 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_projects', '0006_positions_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positions',
            name='type',
        ),
    ]
