# Generated by Django 4.0.2 on 2022-03-15 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_projects', '0008_rename_portfolio_positions_portfolio_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='positions',
            old_name='portfolio_id',
            new_name='portfolio',
        ),
    ]
