# Generated by Django 4.0.2 on 2022-03-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_projects', '0009_rename_portfolio_id_positions_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='positions',
            name='current_market_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
