# Generated by Django 4.0.3 on 2022-03-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_projects', '0010_positions_current_market_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='positions',
            name='position_profit',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='positions',
            name='position_profit_in_percentage',
            field=models.FloatField(default=0.0),
        ),
    ]
