# Generated by Django 4.0.3 on 2022-03-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_projects', '0011_positions_position_profit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='positions',
            name='amount_invested',
            field=models.FloatField(default=0),
        ),
    ]
