# Generated by Django 4.0.3 on 2022-03-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_projects', '0013_portfolio_total_amount_invested_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='total_positions',
            field=models.IntegerField(default=0.0),
        ),
    ]
