# Generated by Django 4.0.3 on 2022-04-03 17:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_projects', '0014_portfolio_total_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='data_for_chart_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0.0), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='labels_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=20), default=[], size=None),
            preserve_default=False,
        ),
    ]
