# Generated by Django 4.0.3 on 2022-04-05 19:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_projects', '0015_portfolio_data_for_chart_array_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='monthly_profit',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0.0), default=[], size=None),
            preserve_default=False,
        ),
    ]
