# Generated by Django 4.0.3 on 2022-04-07 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_projects', '0017_motivationlettermodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MotivationLetterModel',
            new_name='MotivationLetter',
        ),
    ]
