# Generated by Django 4.0.3 on 2022-04-15 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_projects', '0018_rename_motivationlettermodel_motivationletter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MotivationLetter',
        ),
    ]
