# Generated by Django 4.0.3 on 2022-08-19 13:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('database_projects', '0019_delete_motivationletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('16aa8d39-474e-41cc-9a84-58340342d5d5'), editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='positions',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('30d83b46-6ea5-413b-bfb3-a867d7b894a4'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='positions',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
