# Generated by Django 4.0.3 on 2022-08-19 13:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('database_projects', '0022_alter_portfolio_uuid_alter_positions_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='id',
        ),
        migrations.RemoveField(
            model_name='positions',
            name='id',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('215befe0-3793-440b-901e-e0216366e71a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='positions',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d89df07c-de00-4837-a8d5-1a041670b2e9'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
