# Generated by Django 4.0.3 on 2022-08-19 13:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('database_projects', '0023_remove_portfolio_id_remove_positions_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='positions',
            name='uuid',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='id',
            field=models.UUIDField(default=uuid.UUID('57fcbfb3-113c-48ed-b515-f25f8c686ff5'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='positions',
            name='id',
            field=models.UUIDField(default=uuid.UUID('92c4b359-5780-4364-8394-9ae767fd651c'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
