# Generated by Django 4.0.3 on 2022-08-19 13:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('database_projects', '0024_remove_portfolio_uuid_remove_positions_uuid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='positions',
            old_name='portfolio',
            new_name='portfolio_new',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e2d1cb23-1a66-4a86-9037-dccf5baa5bd0'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='positions',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e58fb1ab-c929-41a6-b6ec-e27139e92389'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
