# Generated by Django 4.0.3 on 2022-08-19 13:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('database_projects', '0025_rename_portfolio_positions_portfolio_new_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positions',
            name='portfolio_new',
        ),
        migrations.AddField(
            model_name='positions',
            name='portfolio',
            field=models.ForeignKey(default=115, on_delete=django.db.models.deletion.CASCADE, to='database_projects.portfolio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='id',
            field=models.UUIDField(default=uuid.UUID('abc8a54b-ae77-4404-8d95-a31a3de19040'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='positions',
            name='id',
            field=models.UUIDField(default=uuid.UUID('00c4f31e-f9a6-49ab-8f85-1e1aec986458'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
