# Generated by Django 4.0.3 on 2022-09-02 06:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('database_projects', '0027_portfolio_id_for_chart_alter_portfolio_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e2f710ab-1a5f-4c67-8e7d-bcf5879161fe'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='positions',
            name='id',
            field=models.UUIDField(default=uuid.UUID('63a33c53-04b4-451c-a080-c16a7928d6fd'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='DailyReturn',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('eea39ca6-1728-4168-8b2d-0ec960723175'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('last_price', models.FloatField()),
                ('added_on', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_projects.portfolio')),
            ],
        ),
    ]
