# Generated by Django 3.2.5 on 2021-07-26 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifeevent',
            name='title',
            field=models.TextField(max_length=50),
        ),
    ]
